### ISSUE TITLE
Баги тестовой беты

### ISSUE THREAD

**Issue by K1llMan** [TideSofDarK/PetriReborn#100]
1. Не работает ни починка, ни добыча дерева.
2. Не работает приказ одновременно нескольким юнитам.
3. В апгрейде хаты всплывают какие-то неопределенные значения для цены в золоте.
4. Правой кнопкой мыши квнщик начинает разрушать свои здания.
5. У "Купить акции" иконка не откомпилирована.
6. У "Беруши" иконка не откомпилирована.
7. Странные значения кд у некоторых скиллов.
8. Тултип у башни смерти без перевода.
9. 
   Script Runtime Error: scripts/vscripts/filters.lua:40: bad argument #1 to 'pairs' (table expected, got nil)
   stack traceback:
   [C]: in function 'pairs'
   scripts/vscripts/filters.lua:40: in function <scripts/vscripts/filters.lua:1>
10. Непонятно, где купить ебашню.
11. У "Пропалить" тултип без перевода.
12. Верхняя панель рассчитана на 12 игроков, а не на 14.
13. Пролагивает при перестройке команд в верхней панели.

**Comment by TideSofDarK** [comment]
http://images.akamai.steamusercontent.com/ugc/424815928361005273/3679C39928B5C7BCBA20FFC06AC02DF451B89156/ 
У кого это экшен панел съехал, походу это 16 на 10 или чета типа того.

Еще фриз когда квн становится миниактерм, в панораме сверху когда хуйня меняется.

**Comment by K1llMan** [comment]
лол, если уборщицей взять чужие предметы, а потом попросить передать тебе, то они становятся твоими.
Работает и для предметов квна.
