### ISSUE TITLE
Content of the game

### ISSUE THREAD

**Issue by Drontys** [TideSofDarK/PetriReborn#110]
Уважаемый разработчик спасибо тебе большое что вернул нам elves and trols из варика , но есть проблема в контенте - я понимаю - специально элитарная русская версия этой крутой карты - это здорово, но дота это многоинтернациональная игра, и  мне бы хотелось слышать не только русских школьников, но и американских(например). Проще говоря мне кажется, что контент отталкивает иностранных игроков(почему бы не сделать всё как было- официальных прав на этот режим и эту карту нет ни у кого).(ну и если не сложно упростите хоть как нибудь постройку за эльфов(я помню в оригинале всё было понятней и само обучала новых игроков)
С наилучшими пожеланиями Drontys.

**Comment by TideSofDarK** [comment]
Это никакие ни elves and trolls. Я даже играл в них всего один раз и совсем не помню что там было. Петры они и в варкрафте петры

**Comment by Drontys** [comment]
Пересмотрите пожалуйста http://www.youtube.com/watch?v=RilANoOvhl4 - мне кажется что оригинальная концепция будет приятней комюнити доты. Я имею в виду что когда кто-нибудь додумается выпустить именно такой режим, и вы улетите с пьедестала почёта Custom Games т.к. в доте иностранщины куча(и кто-то очень скоро точно додумается). Вам останется либо скрестить две игры(что возможно, но мне эта мысль не по душе), либо ждать этого дня, либо следует добавить доп режим(что очень сильно поднимет коэффициент не русских игроков) и закрепит вас навсегда в лидерах custom games.Также по правде говоря можно увидеть, что Петры это не очень продуманный (русский(в то время мы не могли переделать её для себя лучше (сейчас можем))) аддон известной нам с вами карте. Оригинал меня очень радовал экшоном всего происходящего, управлением(оно было понятней), про анимацию молчу(она была круть -из хижины ты мог построить дворец -у тебя была целая эльфийская империя). Просмотрите обе игры ещё раз http://www.youtube.com/watch?v=RilANoOvhl4 или http://www.youtube.com/watch?v=w78pFHVhWwA и вы сразу увидите какая лучше(подсказка та где не надо строить башни золота, а золото само прибывает(даже больше с улучшением базы)). Мне очень жаль что вы познакомились  с режимом WallDefence(я его так называю) с Петров, т.к. у меня было чувство, когда я первый раз зашёл игру, что меня кормят сахарозаменителем вместо обычного белого порошка(вы бы поняли эту аллегорию, если бы сами были по лучше знакомы с оригиналом). Если вы скажите что они не похожи - извините, но я рассмеюсь вам в лицо(вот некоторые примеры):строим стену, башни, обороняемся от орков (петросов вам привычнее(концепция полный бред, извините), мастерская - работники - чинят стену, но можно было создать висп-дерево(виспами в реборне может быть сам висп-это же круто), которое само собирает дерево, голда сама подает с улучшенной хаты, что логично(не то что в петросах), так же сходство что у эльфов и квнщиков есть блинк, денай и проч.(там ещё горы сходства). Так что я вам советую(если вы так обожаете своих петросов) добавить новый режим.
С наилучшими пожеланиями Drontys.
P.S. прошу прочитать всё письмо и ознакомиться со всеми источниками для последующей дискуссии

**Comment by Trauin** [comment]
Действительно, было бы замечательно если бы автор выпустил Troll vs Elves. Отдельно от Петров. Так же жду Героев КВН в Петрах, как в оригинальном W3, в данный момент концепция похожа на Troll vs Elves

**Comment by Drontys** [comment]
Ну я примерно про это и говорил)

**Comment by footmah** [comment]
Какая оригинальная концепция? Троли из так называемого "WallDefence" самые молодые. Оригинальная концепция петров это алкоголизм. Тролям если меня не обманывает память 3-4 года максимум, тем же Петрам около 6 про алкогозим молчу т.к карта была не особо популярная(точки фарма алкоголикам находятся в нижней части карты по центру  http://www.youtube.com/watch?v=m6Miqs9qulg) но есть Vampirism первым версиям около 8-9 лет наверное уже(современные вампы http://www.youtube.com/watch?v=fPYOnzP_bTc им лет 7) я промолчу про три таг и те карты которые мало кому были известны .А троли это на мой взгляд что то новое которому небыло предшественников с такой механикой. Так о какой оригинальной концепции ты говоришь? Окей я всем руками и ногами за то чтобы TideSofDarK сделал тролей т.к пользоваться популярностью они будут не меньше чем петры да и кто еще их сделает, никакой инфы ктому же по их разработке нету даже на редите.

**Comment by Drontys** [comment]
Да действительно вы правы (я покопался в интернете и нашёл что петры моложе тролей), но это не исключает того, что сам контент петров туповат(извините за грубость(конечно если вы считаете что квнщики и петросян это очень смешно и увлекательно)).

**Comment by Drontys** [comment]
Ладно эта дискуссия себя исчерпала надеюсь автор карты подумает о создании trols and elves. Всем спасибо)

**Comment by SinZ163** [comment]
Trolls and Elves is being worked on over at [SinZ163/TrollsAndElves](/SinZ163/TrollsAndElves)

**Comment by Drontys** [comment]
Thanks God)))))

**Comment by footmah** [comment]
Нет я изначало считал что петры в варике были неочень поэтому я в них и не играл а играл в тролей и вампов но в доте есть сейчас только петры и вампы. Я тоже хочу чтобы создатель петров в доте намутил и тролей тоже
