### ISSUE TITLE
Падают сервера в течении первых 10 минут

### ISSUE THREAD

**Issue by ovr** [TideSofDarK/PetriReborn#116]
Дисконектит и все

**Comment by ovr** [comment]
Наверное это не к тебе с этим вопросом
Но стата такая
1 из 5 серверов падают на 2 минуте
1 проходит дальше (

**Comment by TideSofDarK** [comment]
Шо делать не знаю, скорее всего проблема в выделенных серверах

**Comment by ovr** [comment]
@TideSofDarK 
Ты про проблему интерфейса (нету всплыв подсказок и кривые часы) знаешь же?

**Comment by TideSofDarK** [comment]
Тоже вольво сломали, я им написал, сказали что решают
