### ISSUE TITLE
Не показываются тултипы (MacOs)

### ISSUE THREAD

**Issue by KODerFunk** [TideSofDarK/PetriReborn#117]
Mac Os 10.10.5 / Графика Intel HD 4000
Не показываются тултипы c артефактов и способностей. 
- Приходится развивать интуицию
- Так и не понял что за график_вверх-скилл у лесопилки

**Comment by K1llMan** [comment]
1. Это косяк вольво, нужно ждать от них фикса.
2. Это лотерея, по графику добавляется ставка.
