### ISSUE TITLE
Набор багов и предложению по балансу

### ISSUE THREAD

**Issue by Vo1ked** [TideSofDarK/PetriReborn#118]
Баги
1.Вард у петей покупается за 25 голда после чего можно использовать безконечно с 0 зарядов
2.ловушка стан получает урон от волны пети(возможно фича)
3.если оба петра ливают то игра не заканчиваеться( а должна бы)
4.невозможно положить вещи в тайник
5.невозможно переложить вещи в инвентаре находясь не на арене(возможно фича)
6.если купить предметов больше чев вмещает тайник то голда заберется но предмет не получишь
7.в башне бабла иногда появляться иконка с возможностю апа на 01-1.5 секунды и пропадает вне зависимости хватает тебе на ап или нет (визуальный баг)
8.тут на миникарте не видно зрилов даже с просветом карты или при просвете от петра
![2015-09-10_00001](https://cloud.githubusercontent.com/assets/14224573/9800978/e0ee9b60-5818-11e5-934c-119f250750c0.jpg)
9.скорость атаки у мини актеров ниже чем у петросянов(возможно фича)
10.иногда если мини актера выкидывает и он пере подключается он показуеться за зрилов с вытекающими последствиями(видно всех зролов,нельзя попасть на тереторию петров)
11.очень сложно у барыги купить предметы для КВн из за очень маленькой зоны покупки (пишет не удалось выбросить предмет)
12. пропали все описания скилов и умений
П.С пока все что вспомнил если ище что вспомню или найду допишу -)
  Предложения
1.немного увеличить количество мобов на 6 арене (драконы) и уменшить их атаку для того что бы там могла качаться 2 петров
2.немного увеличить хп или броню голема так как он убиваеться 2 волшебными топорами , но при этом оставить возможность убийства голема грондом
3.немного увеличить дальность хука или уменьшить зону для квн в верхнем левом углу так как если стать в самый угол то хук туда не достает
4.увеличить бонус урона от прокачки урона у мастера цеха ( так что бы после прокачки петросянов с Самым пиздевым щитом хотя бы коцало)

**Comment by TideSofDarK** [comment]
Спасибо, все чекну. Но коечто из списка фиксануть невозоможно

**Comment by ovr** [comment]
@TideSofDarK Скоро релиз?

**Comment by Vo1ked** [comment]
хотел бы узнать что из заявленных мною ( возможно фича ) такими являются?

**Comment by RumCoon** [comment]
1.Верните возможность качать плюсы хотя бы актёрам. По скорости атаки просадка дикая.
2.Лучше бы уменьшить число КВНщиков, пока вольво не дали хостам возможность лочить команды сразу. Слишком долго игра стартует, все хотят петрами быть.
3.За боссов надо увеличить голду, но делить на всех. Не по 2500 каждому, а чем больше миниактеров, тем меньше голды даст. Такая фишка не даст фармиться на афк-игроках в начале.
4.Было бы неплохо добавить какой-нибудь предмет на минус армор для петров, чтобы хоть какой-то был шанс пробить последнюю стену.

**Comment by Vo1ked** [comment]
RumCoon
2.при желании вполне возможно с другом попасть на петров проблема не в количестве
3.представь ситуацию ты убил 11 зрителей и все они остались играть(или ливнули но делить то надо на всех!) мини актерами(чтотоже маловероятно) ты в надежде дофармить 4к на хук пошол на последнего босса за которого дают 13к убил эго и получил вместо 13к 1900 золота припустим так как с тобой ище 11 мини актеров которы впринципе ничего не могут или ливнули
4.последнюю стену вполне возможно пробить при наличии 4-5 щитов у обоих петров проблема в том что только единичные петры способны собрать по 2-3 щита

**Comment by knetesin** [comment]
сорри за оффтоп, актуально собирал 4 щита, не мог пробить ласт стену, хуком не достать т.к вокруг было около ~15 рабов, так что вопрос единочности явно не актуален, а вот вопрос абуза проходов где может бить лишь 1 петр актуален.

**Comment by Ammodex** [comment]
@knetesin видимо ты плохо собрал 4 щита... Я с 2-мя щитами спокойно пробиваю последнюю стенку

**Comment by knetesin** [comment]
как их можно плохо собрать?:) нет, просто раньше вроде можно было хилят стену в 10 рабочих, в узком проходе и с таким хилом - анреал пробить)

p.s может имеет смысл увеличить цену у хука(сделать грейд как вариант) и сделать чтобы он игнорировал рабов, решит проблему что хук бесполезен а цена внесет баланс + дагер без кд будет юзаться наконец то)

**Comment by K1llMan** [comment]
Неактуально.
