### ISSUE TITLE
Новый скил для мини-актеров

### ISSUE THREAD

**Issue by Vo1ked** [TideSofDarK/PetriReborn#119]
суть скила обычный обзорный вард как в магазине но с такой прокачкой
1  лвл время действия 30 сек перезарядка 30 сек количество вардов 1 дальность установки 100
2  лвл время действия 45 сек перезарядка 30 сек количество вардов 1 дальность установки 100
3  лвл время действия 60 сек перезарядка 30 сек количество вардов  2 дальность установки 200
4  лвл время действия 75 сек перезарядка 30 сек количество вардов 2 дальность установки 200
5  лвл время действия 90 сек перезарядка 25 сек количество вардов 3 дальность установки 400
6  лвл время действия 105 сек перезарядка 25 сек количество вардов 3 дальность установки 400
7  лвл время действия 120 сек перезарядка 20 сек количество вардов 4 дальность установки 600
8  лвл время действия 135 сек перезарядка 20 сек количество вардов 4 дальность установки 600
9  лвл время действия 150 сек перезарядка 15 сек количество вардов 5 дальность установки 800
10 лвл время действия 170 сек перезарядка 10 сек количество вардов 5 дальность установки 800
за основу можно взять ульту эмбер спирита

**Comment by Ammodex** [comment]
это лишним будет

**Comment by K1llMan** [comment]
Миниактеры перерабатываются.
