### ISSUE TITLE
Предыгровой экран

### ISSUE THREAD

**Issue by K1llMan** [TideSofDarK/PetriReborn#123]
Думаю, можно бы было помимо голосования реализовать несколько предложений:
1. Убрать шафл у держателя лобби, а добавить в голосование какой-нибудь пункт типа количества шафлов перед игрой, чтобы не было задержек перед стартом.
2. Добавить для квнщиков выбор уникального скилла.

По интерфейсу думаю прикрутить общий стиль для элементов, правда сейчас вообще неадекватно css себя ведет, можно разве что только накидать внешний вид.

**Comment by TideSofDarK** [comment]
Да, хорошие идеи, надо заняться

**Comment by Leymooo** [comment]
Помоему лучше добавить держателю лобби, "ХОЧУ БЫТЬ ПЕТРОМ" и игры начнут сразу начинаться.

**Comment by K1llMan** [comment]
http://dev.dota2.com/showthread.php?t=179502 возможно поможет от пропадающего Game Setup'а.

**Comment by TideSofDarK** [comment]
Спасибо, запилю.
