### ISSUE TITLE
Хотите ли сделать группу Вк?

### ISSUE THREAD

**Issue by Ammodex** [TideSofDarK/PetriReborn#14]
Добрый день. Долго ждал петры во второй доте, но не суть. У Вас очень быстро растёт аудитория, а с аудиторией, как известно, нужно поддерживать контакт, дабы узнавать про различные баги, пожелания и.т.п. Одного лишь гитхаба будет мало, т.к мало кто захочет здесь регистрироваться здесь, чтобы сообщить о баге или ещё о чём-нибудь. Ну и для поддержания контакта с аудиторией можно сделать либо сайт, либо группу Вконтакте, либо всё вместе. Могу оказать вам помощь в создании группы вк, а именно: Написание новостей, общение с аудиторией, следить за группой и прочее. Если Вас это интересует, то отпишите мне в скайп - latyshspele  , или в вк - https://vk.com/speleivan  .

**Comment by TideSofDarK** [comment]
Опять же, я пока в этом всем не учавствую, так как уже несколько людей начали создавать паблики и я не хочу выбирать кого-то, тем самым обидев других, кто там уже снял гайды и все такое.

**Comment by Ammodex** [comment]
Так я не собираюсь сам делать, Вы делайте - я помогу

**Comment by Ammodex** [comment]
Гайдов нету ещё, вроде

**Comment by Ammodex** [comment]
Не должны же левые люди создавать паблики Вашего режима. У вас должен быть официальный паблик, как у Жизни на арене, к примеру. Там все новости и.т.п, клозы даже устраивают. Вот Вам такое же нужно(имхо).

**Comment by TideSofDarK** [comment]
Уже полно, люди даже статьи пишут, я видел. Пока без паблоса обойдемся, тем более апдейты каждые 30 минут идут. Хочу заняться всей этой темой когда более менее устаканится все.

**Comment by Ammodex** [comment]
Хорошо, а Вы в скайп мне отпишите?

**Comment by knetesin** [comment]
непонятно зачем группа, когда группы могут напрямую ссылаться на баг трекер? помоему тут всё очевидно?)

**Comment by Ammodex** [comment]
люди ленивые, не будут здесь регистрироваться, как следствие, будут исправляться не все баги

**Comment by Ammodex** [comment]
Кстати, не одной группы вк по Вашему режиму нету :)
