### ISSUE TITLE
Голосование за кик игрока

### ISSUE THREAD

**Issue by K1llMan** [TideSofDarK/PetriReborn#142]
Набросал список условий, которые должны соблюдаться для голосования:
- [x] 1. Нельзя голосовать за чужую команду и за себя.
- [x] 2. Нельзя голосовать за хоста. (вероятно можно, если к нему не привязаны никакие функции).
- [x] 3. Нельзя голосовать за игрока чаще, чем раз в полминуты.
- [x] 4. Первое голосование допустимо не раньше четвертой минуты.
- [x] 5. Голосование показывается всем, кроме инициатора и того, кого хотят выгнать.
- [ ] 6. Для успешного голосования голосов должно быть быть больше половины команды.
- [x] 7. Длительность голосования 10 секунд.
- [x] 8. Учитывать только реальные голоса за продолжение игры, а не брать по умолчанию нежелание голосовать за какой-либо из вариантов.
- [x] 9. А для петров - только кик миниактеров если оба пети согласны.

Что-то еще нужно добавить? Как-то может ограничить возможность кикать игроков с наибольшей статой в команде?

**Comment by TideSofDarK** [comment]
Разве что лучше не больше половины а больше двух третьих. А для петров - только кик миниактеров если оба пети согласны.
