### ISSUE TITLE
Баги и баланс

### ISSUE THREAD

**Issue by Ammodex** [TideSofDarK/PetriReborn#16]
При покупке какого либо предмета, есть вероятность того, что купится одна его составляющая и 1-2 рецепта. Продав рецепт(ы) теряется некая сумма. К примеру, я хочу собрать идеальный меч, у меня имеется только гиперубермеч, я кликаю пкм по "идеальный меч" в лавке, у меня покупается меч кладенец и 2 рецепта. Продав эти рецепты мне не хватает денег на идеальный меч, хотя до этого хватало. И этот баг происходит почти со всеми артефактами. 
Если кто-то ливал после распределения команд, то появлялась невидимая хуета(у неё было видно кол-во хп и по ней можно было бить) на месте спавна квнщиков. 
Башни у квнщиков слишком имбовые, даже с самой последней броней они могут ваншотить. Стены, кстати, тоже имбовые. 2-3 стены последнего лвла гарантируют победу. Т,к даже с 2-мя последними щитами их хуй пробьёшь.

**Comment by Ammodex** [comment]
За КВН играть - бред. Все стены, кроме последней, пробиваются как нехуй делать. А вот одну последнюю стену нельзя сломать даже с 3-мя пиздлявыми щитами, имея маску и колу. Так же пробовал ломать вместе с товарищем, у которого был один пиздлявый щит - то же самое. Предлагаю увеличить хп и бронирование у всех стен, кроме последней. А вот у последней стены уменьшить кол-во брони.

**Comment by Ammodex** [comment]
Петры слишком быстро фармят. Предлагаю уменьшить кол-во голды за крипов в 2 раза. В первый день можно без напряга фармить третьих крипов,а на второй - четвёртых.

**Comment by erickskrauch** [comment]
Так в оригинальных петрах можно было делать так же: в 1 ночь стоять на 3 крипах.

**Comment by Ammodex** [comment]
Я, к сожалению, в оригинальные петры мало играл (особенно за петей, играл только за квн). Я на лицензии W3 TFT вообще ни разу не видел петры баланс, только доту, футмана да всякие тд.

**Comment by erickskrauch** [comment]
Я наоборот в этот мод пока ещё не играл (мб на выходных зайду), а вот в War3 только за петей и катал. Конечно для 3 мобов в 1 ночь нужна была некоторая сноровка, но суть была такова, что если зрители не прошареные, то стены падали очень быстро.

**Comment by Ammodex** [comment]
ну а в д2 можно без проблем до 3 крипов за 1 день дойти, даже не напрягаясь. по своему опыту говорю)

**Comment by Ammodex** [comment]
А когда добавите идол юмора, лабораторию и прочее?

**Comment by TideSofDarK** [comment]
Идол юмора скоро. Лаборатория есть начальник цеха

**Comment by Ammodex** [comment]
Кстати, еды же 300 было, а не 250.

**Comment by Ammodex** [comment]
Ещё нашёл баг, когда уборщицу убивают и она возрождается, то у неё обычная моделька осла.

**Comment by TideSofDarK** [comment]
Это да, пофикшу

**Comment by DirolDrops** [comment]
Нашел баг, когда квн может поставить вышку около фарм арены петроса, дать вижн за счет хайграунда и фармить этой вышкой мобов, которые находятся в этой фарм арене ночью и днем

**Comment by Fredd1432** [comment]
Если вылетишь из игры, когда ты мини-актёр... То посмотри что будет, поймешь

**Comment by Fredd1432** [comment]
Вообщем если до вылета мини-актёром мы видели наших петросянов, базу, и тд, но после переподключения это все накроет туманом войны, и видно будет только квнщиков, и контроль над своим "мини-актёром" теряется полностью

**Comment by foxyloves** [comment]
Насчёт последней стены согласен, сколько играю, ниразу не видел, чтобы её ломали петры, слишком она имбовая.
А вот петры на старте очень сильные, но к лейту уже никакие ибо последние стены не могут пробить, а вышки их сносят на раз-два за счёт снятия брони.

**Comment by Ammodex** [comment]
Не знаю, баг ли это, но если играть больше 90 минут, то исчезает интерфейс.

**Comment by Ammodex** [comment]
С хилом пиздец какой-то, один петя ломает, а актёры хилят его, хил без кд почти и мп нихуя не жрёт.

**Comment by Ammodex** [comment]
Когда пети и актёры били хаты, то на хаты юзался 3 спелл джакиро.
![124](https://cloud.githubusercontent.com/assets/12857841/8889525/62e4be40-32ff-11e5-8928-4ee50245e628.png)

**Comment by Ammodex** [comment]
И ещё, добавьте улучшений для таверов, т.к последние тавера нихрена не дамажат петям, если у них есть ситтхи и 2 пиздлявых щита, по 2-3 апгрейда каждой башне. Ну и цену сделать соответствующую. от 1 к голды.

**Comment by Ammodex** [comment]
И добавьте ещё одно улучшение для предприятия, чтоб можно было киборгов (или хз кого) делать, а то эти нихуя не чинят cтену.

**Comment by foxyloves** [comment]
Последнюю стену нельзя снести с 4 трезубцами + 2 последних щита.
О каком киборге речь?
КВН нёрфить надо или очень апать петров.
Сколько играю и победы все были за счёт хука.

**Comment by Ammodex** [comment]
Можно, меня снесли 2 петра, они даже маску не юзали, у них был 1 пиздлявый щит и ситхи, всё. Они тупо стояли и ломали, а актёры их хилили. Таким образом за 2 минуты они тупо вынесли стену. За счёт хука? У тебя плохая реакция, после хука сразу блинкайся и всё. Сколько меня хукали, и не разу не убили.

**Comment by Ammodex** [comment]
Кстати, сделали бы тогда страничку на трелло.ком, если паблик вк не хотите делать.

**Comment by Fredd1432** [comment]
Сделайте так чтобы стену мог хилять только ОДИН юнит, а то бьешь стену а ее лечат по 200 хп

**Comment by nikita131** [comment]
![2015-7-26_5-1-29 937](https://cloud.githubusercontent.com/assets/13502966/8892181/2a777d2c-3354-11e5-96f2-e304adf74b26.jpg)
баг ландшафта ,можно построить выход и петросян его не сломает.
![2015-7-26_5-2-49 774](https://cloud.githubusercontent.com/assets/13502966/8892177/f0a95566-3353-11e5-8f04-77f8c2f4986e.jpg) 
![2015-7-26_5-1-48 580](https://cloud.githubusercontent.com/assets/13502966/8892179/208995c0-3354-11e5-8378-d40e5f19130e.jpg)
еще баги ландшафта
![2015-7-26_5-0-17 609](https://cloud.githubusercontent.com/assets/13502966/8892186/7d2b5516-3354-11e5-8b0d-d0d903c0ea91.jpg)

**Comment by TideSofDarK** [comment]
Замечательно, пофикшу

**Comment by Fredd1432** [comment]
Еще 1 баг или не доработка, вообщем глазок квнщиков палит инвиз петросянов даже для нейтралов, ну крч  если под инвизом зайти на крипов, и квнщик использует глазок, то крипы начнут тебя в инвизе карасить

**Comment by Ammodex** [comment]
Ещё раз попрошу, сделайте. по 2-3 апгрейда каждой башне.

**Comment by madf12** [comment]
Только что плеил, дефал стену, дали стан и меня убили первой пассивкой два петра пока я стоял в стане. Не знаю, должно ли быть так или нет

**Comment by vladhumi** [comment]
появился баг со стаканьем убер маски смеха у пети трезубец на 2 ночь. слишком много фарма за стенку

**Comment by nikita131** [comment]
на 
![2015-7-29_12-28-15 249](https://cloud.githubusercontent.com/assets/13502966/8954488/97c1d50c-35ee-11e5-99af-93cd6fc5ecf9.jpg)

**Comment by madf12** [comment]
![osvjpxd 1](https://cloud.githubusercontent.com/assets/13491011/9022197/db1c42e6-3874-11e5-9d5f-ca63fb4b3853.jpg)

**Comment by madf12** [comment]
Сегодня квнщик после старта игры, перезашел и реснулся с моделькой вайпера
![2015-08-02_00001](https://cloud.githubusercontent.com/assets/13491011/9028151/609dad30-3977-11e5-87c4-48afdd2346a3.jpg)
