### ISSUE TITLE
Баг с получением золота с мешочка с золотом.

### ISSUE THREAD

**Issue by Kailo97** [TideSofDarK/PetriReborn#17]
На значке 1 способности идет отсчет 6 секунд, если навести мышку там указано, что перезарядка 5,725 секунд. А баг в том, что после конца перезарядки, он не использует способность автоматически сразу, а только где-то еще через 3 секунды, и получается что доход идет каждые ~9 секунд, а не ~6.

**Comment by TideSofDarK** [comment]
В некст апдейте все будет, баг уже пофикшен
