### ISSUE TITLE
Требуется изменения цен на шмотки.

### ISSUE THREAD

**Issue by foxyloves** [TideSofDarK/PetriReborn#24]
Слишком не адекватные и не логичные цены у петров на вещи, особенно на щиты.
Щит небес за 19500 голды, даёт 1200 брони, когда, как 3 щита природы, вместе дадут 1500 брони за 19650.  (итого +300 брони всего за 150 голды)
Так же нету смысла в книге апающий дамаг ибо за 5000 голды, всего 616 атаки это очень мало, когда можно за 3386 голды купить Волшебный топор и он даст 1900, что в 3 раза больше.
Очень не понятна цена на камень силы, ведь за свои 7200 голды, она даёт всего 55 силы, когда книга силы за 2300, даёт 40 силы.

**Comment by TideSofDarK** [comment]
Окей, скоро пофикшу
