### ISSUE TITLE
Срочно фикс начальника цеха!

### ISSUE THREAD

**Issue by Ammodex** [TideSofDarK/PetriReborn#25]
Срочно фикс начальника цеха!
С прокачанными нанотехнологиями башни бьют по всей карте! Можно фармить даже крипов, имея глазок.

**Comment by Ammodex** [comment]
вот уже вторую игру зрилы петров на их спауне убивают

**Comment by Ammodex** [comment]
аааххахахах, да это просто пиздец) петя только появился, его сразу ебнули :(

**Comment by TideSofDarK** [comment]
Пофикшено
