### ISSUE TITLE
Changelog в описании карты

### ISSUE THREAD

**Issue by samenick** [TideSofDarK/PetriReborn#28]
Пожалуйста, ведите лог разработки с описанием изменений прямо в клиенте. Дата последнего обновления видна, а за ими нало переться в гитхаб. Спасибо

**Comment by TideSofDarK** [comment]
Всмысле? А это что? ![s](http://puu.sh/jd1go/e3ddf9bcca.png)

**Comment by samenick** [comment]
Я слепой, да. Клоз
