### ISSUE TITLE
Скрыть дефолтную панель скиллов с помощью флеша

### ISSUE THREAD

**Issue by TideSofDarK** [TideSofDarK/PetriReborn#29]
Мне тут пример дали, по словам чувака тут скрывается почти все, кроме самой панели скиллов. https://gist.github.com/SinZ163/71a6ba1cbc901c44b08e
Короче это можно взять за основу и переписать под наши нужды, пока вольво не перенесут UI на панораму.

**Comment by K1llMan** [comment]
Scaleform will initially remain functional during the Beta, but Custom Games that use Scaleform or ActionScript will eventually stop working.

Оно все равно скоро отвалится, придется свой велосипед дописывать. Не знаю, стоит вкладывать силы в то, чему осталось жить месяц.

**Comment by TideSofDarK** [comment]
Разве это настолько геморно? Самая сложная часть всего этого по-моему компиляция swf, лол.
