### ISSUE TITLE
Баланс...

### ISSUE THREAD

**Issue by MoNETka** [TideSofDarK/PetriReborn#31]
Зачем башню голды понерфили? Теперь стенку апать, чтобы она петров держала просто нереально, они очень быстро фармят, и ,тупо физически не успеваешь апать эту стену...В итоге тебе разносят всю базу и гг вп...За квн уже не резон ирать...

**Comment by Ammodex** [comment]
полностью согласен, это пиздец какой-то. За 30 минут не смог еле-еле апнул последнюю стену, в то время у пети было 4 трезубца, ситхи и пиздлявый щит.
