### ISSUE TITLE
Зачем так нёрфить петров?

### ISSUE THREAD

**Issue by foxyloves** [TideSofDarK/PetriReborn#34]
Я вот одного не могу понять, сам автор, играл хоть раз за петров, раз так насилует их, теперь петры это инвалиды + ещё и хук бесполезен ибо вот таких мест полно, где не достать квнщиков.
![2015-07-26_00001](https://cloud.githubusercontent.com/assets/13489856/8895858/6253f688-33f1-11e5-8faa-c000d464efe0.jpg)

Нужно, как минимум увеличить радиус хуку и вернуть нормальную голду с крипов.

**Comment by TideSofDarK** [comment]
Хуйня, специально сегодня после патчей на петрах играл несколько раз, все заебись было. Просто у вас там попадаются криворукие мудаки. Если кто-то орет дайте петю, лучше бы давали.

**Comment by foxyloves** [comment]
что хуйня?
места где можно сныкатся от хуков?

**Comment by TideSofDarK** [comment]
Ну да, хуйня. Если тебе приходится покупать хук чтобы выиграть то ты слабак, который не умеет правильно фармить. Хук вообще не какая-то цель на игру для петров, изначально это вообще штука чтобы из текстурок ливеров доставать. Но от него и страдают дауны, которые отстроят базу а потом свернут игру и ждут когда выход достроится. А то что есть места где хук не достает - ну радость для любителей свернуть игру, ну и хуй с ними.
