### ISSUE TITLE
Шмотки для квнщиков

### ISSUE THREAD

**Issue by ToshuK** [TideSofDarK/PetriReborn#35]
Почему не добавишь вещи для квнщиков, как были в варкрафте, в карте Петры баланс? - Ведь это было действительно нужно, там были очень полезные вещи... Не рассматривал этот вариант?

**Comment by ToshuK** [comment]
И хук если убрать - и карта огонь будет!

**Comment by TideSofDarK** [comment]
Будет магазин для квн.
Но почему у вас всех так жопа от хука горит? Вы любители построиться а потом свернуть игру и ждать когда выход достроится? Лично я когда за КВН играю и петя хук покупает - начинается веселье.

**Comment by ToshuK** [comment]
Нет, мы любим застраивать петь и смотреть на их беспомощность... Кстати накинь дамага таверам, ибо петь чето совсем не коцает...

И почему такие плохие иконки и модели строений? Ведь есть гаразда лучше и осмысленней...

**Comment by TideSofDarK** [comment]
Дамага достаточно, там чуть ли не по косарю с одной ебашни с грейдами.
Ну предлагай модельки лучше и осмысленее, я сделаю.

**Comment by ToshuK** [comment]
Ну я ставил по две каждой - им как-то до одного места было)) А поставить еще - не хватало места, становился в основном на маленькие территории. Попробую на больших или с другом, может действительно я мало ставлю.

Как тебе лучше модели предложить? Кинуть скрины или ... ?

**Comment by TideSofDarK** [comment]
Ты их где смотреть то будешь? Если в ассет браузере то сразу путь кидай мне с подписью для чего это
