### ISSUE TITLE
Новые баги после обновы.

### ISSUE THREAD

**Issue by foxyloves** [TideSofDarK/PetriReborn#38]
![2015-07-27_00001](https://cloud.githubusercontent.com/assets/13489856/8897911/aee85e2e-3425-11e5-9d7c-be5c4c9b49f3.jpg)
![2015-07-27_00002](https://cloud.githubusercontent.com/assets/13489856/8897912/aeeb00ca-3425-11e5-9d5e-e0b4a9aa9bdc.jpg)

нельзя построить башни, начальника цеха и добывать дерево.

**Comment by TideSofDarK** [comment]
Да-да, работаю над этим.

**Comment by meshok275** [comment]
реально нет иконок постоянно, 3 игру заупскаю добавляйтесь кстати в стиме ник Фанат КВНа или g_d_e

**Comment by meshok275** [comment]
Пока не заценил, но если добавлен обмен дерева и золота то хост ты гениален! А хук зря убрали у КВН я постоянно его тарил)))

**Comment by nikita131** [comment]
пропала иконка сноса здания в самом начале игры
![2015-7-27_16-0-4 339](https://cloud.githubusercontent.com/assets/13502966/8906661/f99a703a-3478-11e5-83e6-93e1faa146a7.jpg)
еще у моего друга похожее если ставишь больше 1 глазюка

**Comment by TideSofDarK** [comment]
Не должно быть такого больше.
