### ISSUE TITLE
Баги прокачки

### ISSUE THREAD

**Issue by foxyloves** [TideSofDarK/PetriReborn#39]
нельзя на полную вкачать хилку, после 5000 дальше не даёт.
нельзя на полную вкачать стан дальше 19 не даёт.
![2015-07-27_00003](https://cloud.githubusercontent.com/assets/13489856/8898928/dbb32abe-3435-11e5-8930-b5c4f77431b8.jpg)
![2015-07-27_00004](https://cloud.githubusercontent.com/assets/13489856/8898927/dbb21f3e-3435-11e5-8f37-d129ff0cca91.jpg)

**Comment by foxyloves** [comment]
У мини-актёров тоже нельзя хил вкачать после 5000 + после 40 уровня нечего апать и висят 10 очков.

**Comment by TideSofDarK** [comment]
Это визуальный же баг.
