### ISSUE TITLE
Нельзя выйти из окна построек.

### ISSUE THREAD

**Issue by foxyloves** [TideSofDarK/PetriReborn#40]
![2015-07-27_00005](https://cloud.githubusercontent.com/assets/13489856/8898996/20da851e-3437-11e5-8b88-a68f0a4d3a10.jpg)

**Comment by foxyloves** [comment]
У мини-актёров тоже нельзя хил вкачать после 5000 + после 40 уровня нечего апать и висят 10 очков.

**Comment by TideSofDarK** [comment]
Пофикшено.
