### ISSUE TITLE
нерф брони нужен

### ISSUE THREAD

**Issue by Ammodex** [TideSofDarK/PetriReborn#41]
пиздец какой-то, занял участок, который чуть выше и левее спауна квнщиков. Ну там можно вышки с 2-ух сторон поставить. Вооот, строился с другом - я стену, он - вышки. Он построил по 10 вышек с обеих сторон, по 4 огненных, по 2 снижающих броню и по 4 ебашни. Петя купил себе 2 щита (хз каких) и тупо стоял и бил стенку. 20 вышек его нихуя не пробили.

**Comment by nikita131** [comment]
можно сделать чтобы минус армор у тавера который томба увеличивался со временем ,а  то минус 1300 армора ко 2 ночи жестко,но к 90 минуте 1300 это мало и еще нужно поднять стартовую бронь пети на 1!

**Comment by TideSofDarK** [comment]
Скоро переработаю ебашню под лейт-гейм.
