### ISSUE TITLE
Как бы просто вопрос

### ISSUE THREAD

**Issue by ExorcistF1** [TideSofDarK/PetriReborn#43]
Бил стену петей под конец игры и КВНшика за этой стеной ваншотнуло, как х3 ... даже скриншот не сделал, но он очень возмущался. Вот такие херни как репортить? Мож реплей как нить можно взять или гайд по таму как правильно репортить есть, карта понравилась хочу помочь.

**Comment by foxyloves** [comment]
КВНщика убила первая абилка петра.

**Comment by TideSofDarK** [comment]
Закрываю, ибо да, пассивка петра.
