### ISSUE TITLE
Баг и ещё кое-что

### ISSUE THREAD

**Issue by Ammodex** [TideSofDarK/PetriReborn#44]
Если смотреть на постройки (неважно, на свои или на союзников) можно увидеть 2 хп бара, вместо одного. Второе - можно руинить игру союзникам, ставя свои стены или любые постройки около входа на хг.

**Comment by TideSofDarK** [comment]
Вот про такие вещи с хп барами - где скриншот? Скорее всего тебе так показалось из-за высоты хпбара над моделькой. А второе не понял, каким образом?

**Comment by Ammodex** [comment]
Вот таким образом.

![228](https://cloud.githubusercontent.com/assets/12857841/8923798/6e817e72-3517-11e5-957b-db9e71d4424d.png)

**Comment by Ammodex** [comment]
Если поставить стенку за этой хатой, то петя спокойно может пройти.

**Comment by TideSofDarK** [comment]
Так, и ты предлагаешь типа если начал строиться где-то то все - твое единственное забитое место?

**Comment by Ammodex** [comment]
Нет, постройки можно ставить даже если это место заняли. Ставить можно только на лестницу и только на территорию с текстуркой дороги.
