### ISSUE TITLE
Не исчезла проблема с пропажей кнопок построек.

### ISSUE THREAD

**Issue by foxyloves** [TideSofDarK/PetriReborn#45]
Собственно опять пропадают кнопки башен, начальника и добычей дерева.
![2015-07-28_00033](https://cloud.githubusercontent.com/assets/13489856/8938132/65a68628-3565-11e5-9ec6-5ccb4b975f8e.jpg)
![2015-07-28_00034](https://cloud.githubusercontent.com/assets/13489856/8938133/65a769da-3565-11e5-87ef-dc7a918a28bc.jpg)

**Comment by TideSofDarK** [comment]
Пиздец заебался сука сука блять блять. Ну ладно, буду смотреть с чем это связано.

**Comment by foxyloves** [comment]
Актуально до сих пор.

**Comment by TideSofDarK** [comment]
Актуально то актуально, вы последовательность действий говорите при которой эта хуйня появляется. Потому что я как по кнопкам не долблю - у меня не получается это вызвать.

**Comment by TideSofDarK** [comment]
Если ты хост можно было бы и лог консоли давать даже, возможно поможет.

**Comment by foxyloves** [comment]
Да, часто такое, когда я хост.
Кину логи, как опять будет проблема.
Но обычно это из за постройки чего-то.
