### ISSUE TITLE
небольшое предложение, хз было не

### ISSUE THREAD

**Issue by combichristt** [TideSofDarK/PetriReborn#46]
сделать ограничение на юнитов, чинящих стену, поскольку снести таких анриал, а хуком не попадешь, поскольку типы просто блочат себя юнитами
и ещё кое-что, когда перекладываешь 2-ую колу в инвентарь, то она не стакается с первой, только если вручную

**Comment by jappi** [comment]
Юнитов и так ограничивает пространство. Т.е. на карте полно мест где стенку могут чинить только 2 рабочих, а есть, например, хитрые места, где могут чинить 4 и больше. Это уже весьма сбалансированно. А на счёт хука, его покупают только отбитые либо ради фана либо чтобы вытащить с хг (собственно с этой целью хук и ввели). в любом случае петросян на 4 ночь при правильном фарме сможет снести тб с максимальными заплатками даже если его будут чинить.

**Comment by nikita131** [comment]
нужно придумать что-то с армором. Ибо ко 2 ночи тебя ваншотит томба ,а к 4 ночи наносит 0 урона
