### ISSUE TITLE
Доработки интерфейса

### ISSUE THREAD

**Issue by K1llMan** [TideSofDarK/PetriReborn#48]
Пока слишком бедное API на JS. 
1. Нет возможности проверить атрибут скилла функцией IsDebuff(), поэтому невозможно выделить из списка скиллов в панель баффов.
2. Для полоски опыта нужен доступ к таблице опыта на уровни + какое-то событие, которое вызывается при получении опыта.
3. Насчет панели с выделенными юнитами пока не могу найти доступ к иконкам. Надо погуглить еще по поводу возможной реализации.

**Comment by TideSofDarK** [comment]
1. Дебаффами и баффами являются модиферы а не скилы но да, не нашел в АПИ даже упоминаний всей этой хуйни. Плохо.
2. Запилю.

**Comment by TideSofDarK** [comment]
Насчет первого. НУУУУ, конечно по идее можно их так же отправлять, но блять, мы итак уже слишком много хуйни отправлять собираемся.

**Comment by TideSofDarK** [comment]
Добавил ивент пересылки таблицы уровней.

**Comment by TideSofDarK** [comment]
> UI Example: Added a display of buffs to the example HUD.
> Смотри что там в екземпле

**Comment by K1llMan** [comment]
Ты ведь можешь возвращать из lua не только значения, но и ссылку на функцию? Предлагаю сделать ход конем, пока они API не фиксанут, - вызывать функции прямиком на lua через враппер, ссылку на который можно передать в js. 
http://stackoverflow.com/questions/1791234/lua-call-function-from-a-string-with-function-name

По баффам они как раз вовремя подсуетились, сегодня сделаю.

**Comment by TideSofDarK** [comment]
Бля, чет я не уверен что так получится. Ну, попробуем.

**Comment by K1llMan** [comment]
Добавил баффы. Осталось сделать отображение стоимости скиллов и опыта. Тогда будет вполне играбельно. Заодно разобрался с отображением иконок.

Потом надо будет допиливать фичи типа панели с выделенными юнитами, юзанье скилла по кнопке всеми юнитами и т.п.

**Comment by K1llMan** [comment]
![skills](https://cloud.githubusercontent.com/assets/13403439/9002748/81d51a3c-3770-11e5-9922-b13293e31f0b.png)
Подумал над панелью скиллов по твоему предложению. В принципе тогда не придется даже прикручивать новый интерфейс, просто дополнительную панельку. Тогда сделать в скиллах, которые открывают меню, вызов события с передачей скиллов для отображения в верхней панели. Нижние скиллы остаются с постоянными хоткеями на qwerty, верхние развернуть от 1 до 0, максимум в 10 штук, чтобы не перегружать. Также скиллы починки и добычи дерева вынести на контекстную обработку нажатия правой клавиши мыши соответственно по зданию и по дереву. Пока не придумал, как эти менюшки будут скрываться, возможно по таймауту.

**Comment by TideSofDarK** [comment]
Так нажал Q - скилл затогглился(зеленым обвелся) - меню появилось. Нажал еще раз - закрылось. Насчет цифр сомнения, вдруг большинству неудобно будет.

**Comment by TideSofDarK** [comment]
Но новый интерфейс нужен потому что все еще есть апгрейды которые на дефолтном баре находятся, для них стоимость в еде и дереве нужна.

**Comment by K1llMan** [comment]
> Нажал еще раз - закрылось. 

Я думаю, что проблема может возникнуть, если нажать другой скилл с меню. Или там автоматом прерывается предыдущий, когда следующий прожимается, что рамка убирается?

**Comment by TideSofDarK** [comment]
Не понял. Другой скилл с какого меню?

**Comment by K1llMan** [comment]
С этого же самого. Я боюсь, что рамка будет оставаться на первоначально вызванном скилле, а меню уже от второго будет показываться. Придется как-то обходить такую ситуацию.

**Comment by TideSofDarK** [comment]
Не, все нормально будет.

**Comment by nikita131** [comment]
во-1 нельзя вставлять  (ctrl+ v)
во-2 когда меняешь вещи в инвентаре местами сбивается добыча дерева . тоже самое когда юзаешь мешок из инвентаря.

**Comment by K1llMan** [comment]
Надо определиться, что будет выводиться в кастомную подсказку для скиллов.
1. Название скилла.
2. Описание.
3. Дерево зависимостей.
4. Цена в ресурсах
5. Кулдаун.

Еще что-то должно быть? Не факт, что возможно вытащить все, что есть в реальных подсказках.

**Comment by TideSofDarK** [comment]
#80
![XYU](http://puu.sh/jwS7W/73cd624ccb.jpg)
![XYU](http://puu.sh/jwSdJ/fe0c48ecb0.jpg)

Такие дела.

**Comment by K1llMan** [comment]
Так это ожидаемо. Флеш же находится на самом нижнем уровне.

**Comment by TideSofDarK** [comment]
Ну типа да, но нельзя же в таком виде отправлять

**Comment by K1llMan** [comment]
Ну могу еще панельку вещей запилить, только хз, какие там проблемы всплывут и сколько времени займет.

**Comment by TideSofDarK** [comment]
Мне чувак добавился, говорит панораму ебашит, на тебя направил, как в стим зайдешь попизди с ним

**Comment by TideSofDarK** [comment]
#82 
1) Длительность баффам
2) OnHover баффам с их названием и описанием
3) Кажись не показывается больше одного баффа(могу ошибаться)
4) Кнопка шопа
5) Иконки в инвентаре маленькие слишком
6) Чтоб тултипы показывались нормально с первого раза
7) Список юнитов(полюбому нужен) как и нажатие по портрету
8) Общие команды для юнитов
Ебануться список, да

**Comment by K1llMan** [comment]
2) Работает, но криво. Подсказка выводится по наведению на границу.
7) Предлагай решение.

**Comment by K1llMan** [comment]
#84 
1. Добавил отображение длительности оверлеем.
2. Уже показывается.
3. Как можно потестить?
4. Нужны команды для открытия шопа, без них не имеет смысла прикручивать кнопку.
5) Увеличил размер.
6) Пофиксил.
7) Ну ты в курсе, что я хз, как сделать. Может кого-нибудь напрячь знающего.
8)  Пока не получается сделать. Покручу еще последовательность команд, но ничего пока не гарантирую.

Также пофиксил стили под разные разрешения, чтобы подгружались подходящие под разрешения картинки задников и ничего не уезжало.

**Comment by TideSofDarK** [comment]
@K1llMan 
Короче, сделал хуйню которая хайдит флешевый инвентарь и абилки. Взамен юзаются твои.
Пожертвовал на данный момент только тултипами в квик-байе. В крайнем случае их тоже можно сделать, посылая ивент с флеша на сервер, с сервера на панораму, лол.

От тебя нужно почистить проект от лишнего говна и подогнать под все разрешения и посути наверное с интерфейсом все. Если ты еще чего то серьезного не найдешь.

**Comment by K1llMan** [comment]
#87
Пофиксил. Только одна фигня осталась со стешем на флеше. Если скрывать инвентарь, то и его тоже надо отключить.

**Comment by TideSofDarK** [comment]
Добавил курьера, пиздец костыльного, ну хоть что то, потому что дефолтного юзать невозможно. 
Тебе нужно добавить чтобы стеш показывался если курьер выделен. Если не будет работать перемещение со стеша на курьера возможно там фильтр ебну.

![dick](http://puu.sh/jD45i/76cbf40da3.png)
И вот это пофиксить.

**Comment by K1llMan** [comment]
Это у тебя какой-то косяк, у меня все нормально отображается.

**Comment by TideSofDarK** [comment]
Короче от тебя нужно только опять же немного оптимизации, потому что игра зависает на полсекунды при обновлении панели скиллов за КВН + общие команды для юнитов выбранных. Главное сделать чтобы автокаст автоматом нажимался на всех
