### ISSUE TITLE
Выход раньше 24ой минуты.

### ISSUE THREAD

**Issue by Kailo97** [TideSofDarK/PetriReborn#49]
Вроде все знаю о баге, но что-то темы тут об этом не нашел.
http://www.youtube.com/watch?v=y7MF7Uoapvo&feature=youtu.be
выход поставил на 22:19 по игровому времени

**Comment by TideSofDarK** [comment]
Пока не знаю что с этим делать. Нет идеального способа получить игровое время. Разве что свои часы делать, посмотрим.
