### ISSUE TITLE
/

### ISSUE THREAD

**Issue by Suprenok** [TideSofDarK/PetriReborn#50]

**Comment by madf12** [comment]
А что прикажешь делать тем кто достроил выход раньше остальных? Ливать? Но ведь игра все еще не выиграна, а ждать остальных непонятное количество времени, как-то не очень хочется

**Comment by TideSofDarK** [comment]
В петрах баланс если выход построен - выигрывают все. Я считаю что так и должно быть.

**Comment by Suprenok** [comment]
MadF12, незнаю может охотится? :D

**Comment by Suprenok** [comment]
TideSofDark, я просто предложил просто в первой дотке был похожий режим!
