### ISSUE TITLE
Ебнутая идея

### ISSUE THREAD

**Issue by Ammodex** [TideSofDarK/PetriReborn#51]
8 полностью одинаковых зрилов - пиздец скучно. И я тут подумал, можно это всё кое-как разнообразить. Вместо 8 клокверков сделать 8 разных героев. И у каждого героя будут свои минусы или плюсы в постройках. К примеру, сделать трента, который сможет строить самые прочные стены, но не будет иметь башен атаки.

**Comment by madf12** [comment]
Ебнутая идея, а теперь представь что будут делать пети, когда 2-3 друга с такими персами (у одного нет вышек, но есть ништяковая защита, у другого наоборот, а у третьего к примеру золото ручьем течет) построятся на одном споте. Пети просто будут насасывать и все

**Comment by TideSofDarK** [comment]
Будет разнообразие но не в таком виде. К примеру в начале можно будет выбрать уникальный талант, как в петрах баланс.
