### ISSUE TITLE
Не покупаются шмотки за квнщиков

### ISSUE THREAD

**Issue by Ammodex** [TideSofDarK/PetriReborn#52]
Поставил барыгу, подошёл к нему вплотную, открыл меню, выбрал ловушку, жму по ней пкм - нихуя не покупается.

**Comment by TideSofDarK** [comment]
Скриншот места где поставил?

**Comment by Ammodex** [comment]
Я уже в 3-ёх местах строился, везде такая хуета.

**Comment by TideSofDarK** [comment]
Ты уверен что не покупается? Они стакаются если чо. У меня проблем нет, я хз. Если ты хост то посмотри, может в консоли ошибки есть

**Comment by Ammodex** [comment]
Всё решилось, нужно было вплотную встать к барыге.
