### ISSUE TITLE
хост постоянно кикает меня

### ISSUE THREAD

**Issue by nikita131** [TideSofDarK/PetriReborn#53]
хосты пети часто кикают потому что не могут сломать.... придумай что-то, хотя ты тут вроде ничего не сможешь седать

**Comment by TideSofDarK** [comment]
Часто что, ливают может быть? С этим хуй что сделаешь, тут хостботов как на айсикапе нет. Короче вообще если знаешь, что ливать не будешь - хости. Если хочешь играть за квн и собираешься ливнуть если тебя ебнут - присоединяйся.

**Comment by madf12** [comment]
Если ты хост, то наверн можно кикать через консоль командой kickid. Может он это имел ввиду?

**Comment by TideSofDarK** [comment]
Ну, я искал варианты блокировки команд дефолтных и пока не нашел. Людей спрашивал, тоже ничего дельного.
