### ISSUE TITLE
Баги\Странности

### ISSUE THREAD

**Issue by cvxvpdev** [TideSofDarK/PetriReborn#55]
Вообщем сегодня играл в Петров,свернул дотку пока загружался,открыл,меня убили и я стал псевдоКВНщиком себя на карте не видел и других петь,фармить споты мог петров,видел всех КВН,слышал что говорят и пишут.
http://5.firepic.org/5/images/2015-07/30/l9mqgfx8fzje.jpg
http://5.firepic.org/5/images/2015-07/30/xhlf20wuby0m.jpg
Ещё баг можно блинком в деревьях засесть.Нашел место :dancer:

**Comment by TideSofDarK** [comment]
Реконнектился?

**Comment by TideSofDarK** [comment]
Всмысле баг произошел после реконнекта или без него вообще?

**Comment by cvxvpdev** [comment]
После реконнекта

**Comment by TideSofDarK** [comment]
Ну да, есть такое. Займусь чуть позже.

**Comment by diegogmx** [comment]
damn, i would help if i understood anything

**Comment by TideSofDarK** [comment]
Please, if you have bug then describe it here.

**Comment by diegogmx** [comment]
id rather fork but i cant uderstand what the bugs are

2015-08-01 6:12 GMT-03:00 TideSofDarK notifications@github.com:
