### ISSUE TITLE
Поставь ограничение на починку юнитов.

### ISSUE THREAD

**Issue by foxyloves** [TideSofDarK/PetriReborn#56]
10 чинильщиков это через чур, в двоём с 3 щитами последними не смогли перебороть стенку.
![werwerwerwerwerwerwerwerwer](https://cloud.githubusercontent.com/assets/13489856/8988890/82d9fb0c-36f1-11e5-942e-9ab8b7a864b3.jpg)

**Comment by Kidokyfe** [comment]
+1 Актуально

**Comment by TideSofDarK** [comment]
Чинить могут максимум 4 рабочих, от остальных хп не прибавляется
