### ISSUE TITLE
Баги/предложения

### ISSUE THREAD

**Issue by jappi** [TideSofDarK/PetriReborn#6]
приведу список как мне видится баланс этой игры
Шмотки:
1) "Самый пиздёвый щит" за 28к даёт всего на 50 армора больше чем предыдущий и требует итем атаки(?)
2) Для крафта "тризубца" требуется рецепт всего за 2500, а итем даёт 5к атаки плюс, сделай как с другими что надо 2 мьёлнира например
3) На книгах напиши сколько они дают силы/атаки
Петросы:
1) Апни 2 арену по дмг/хп, т.к. с первых секунд можно на неё бежать и получать профит.
2) Атака мобов с 5 и 6 неадекватна даже по ласт армору.
3) Цены на армор высоки (щиты)  и в них нету смысла при фарме т.к. можно обойтись Basic армором
4) На арену где драконы добавь ещё пару драконов иначе они фармятся не нанося урона
5) "Магический щит" дающий 2 инвул не нужен в игре. Достаточно 13 секунд от маски и 8 от колы.
6) Масляковы ваншотят даже ласт армор с дарт вейдером 
7) Просвет слишком много светит и в первую ночь можно найти всех
Пока всё что смог вспомнить

**Comment by TideSofDarK** [comment]
Спасибо, буду разбираться

**Comment by jappi** [comment]
Если нажать на выход не имея нужного кол-ва ресурсов то спишется что есть и начнётся кулдаун 500сек на выход.
![123](https://cloud.githubusercontent.com/assets/13433394/8803314/e37c2e64-2fce-11e5-93f5-845eac397615.jpg)

В этом месте не добываются деревья

**Comment by jappi** [comment]
![2015-07-22_00001](https://cloud.githubusercontent.com/assets/13433394/8818901/5a441874-304f-11e5-91fd-efe8729918d7.jpg)
![2015-07-22_00002](https://cloud.githubusercontent.com/assets/13433394/8818902/5a5e941a-304f-11e5-9b7c-180eab23d651.jpg)
2 хг с местами для построек

**Comment by TideSofDarK** [comment]
Окей, залатаю.

**Comment by madf12** [comment]
Вроде незначительный баг, но все же, если кол-во символов в стоимости (голд) превышает 4 символа, то влазят только первые три символа, остальные находятся под изображением скила

**Comment by TideSofDarK** [comment]
Это баг интерфейса валв. @K1llMan трудится над новым интерфейсом.

**Comment by samenick** [comment]
Добавьте голд в описание скила тогда. Я чуть кирпич не выложил, когда увидел что голем не апается

**Comment by TideSofDarK** [comment]
Это костылем будет, не добавим. Дождитесь, как я с @K1llMan разберемся как спрятать в пизду дефолтную панель скиллов и будет у вас все хорошо.

**Comment by samenick** [comment]
Тогда зачем стоимость в еденицах дерева там?

**Comment by TideSofDarK** [comment]
Потому что дерево это уже костыль. А золото как бы не костыль, но вальве хуесосы и не сделали чтобы оно нормально отображалось больше трех знаков.

**Comment by samenick** [comment]
Так костыль на дерево можно, а на голд нельзя? Какие-то изберательные костыли у вас

**Comment by TideSofDarK** [comment]
Нахуя мне делать кастомный голд когда он встроенный есть? Я говорю, вскоре все будет заебись, пока терпите.

**Comment by samenick** [comment]
Это даже не смешно. Надо сейчас, а не неизвестно когда-нибудь потом

**Comment by TideSofDarK** [comment]
Ты ебнутый? От того что нулик не видно, никто кроме тебя инфаркт не схватит, к тому же такая хуйня не потому что я криворукий, а потому что вольво не поддерживают четырехзначные числа в голде. Как я сказал - @K1llMan каждый день работает над интерфейсом, ни мне, ни ему нихуя никто не платит, поэтому наберись терпения.

**Comment by samenick** [comment]
Да, нулик. Апгрейд стоит >1000, а значит еденица в начале числа уже не еденица? Ок.
Я понимаю, что за это никто не платит. Брызгать слюной не надо

**Comment by TideSofDarK** [comment]
Блять, едЕница в начале? Не видно ту, что в конце. 
Короче, я тебе сразу сказал, баг вольво, мы стараемся не то что исправить, а вообще свое все написать чтобы точно подобных проблем не было, а ты продолжаешь приебываться.

**Comment by nikita131** [comment]
1)очень нужно сделать так чтобы вещи в инвентаре можно было менять местами !!во время игры нельзя вставлять сообщения только писать самому.
2) выход подороже

**Comment by jappi** [comment]
![2015-07-28_00001](https://cloud.githubusercontent.com/assets/13433394/8935688/acf58c0e-3556-11e5-87d4-f9af0ddfa752.jpg)
С новым апдейтом можно строить здания которые являются объектами через них нельзя пройти и сломать. Если не хватает ресурсов можно поставить в очередь построек тогда их будет видно, если строить по 1 то построек не видно но место непроходимо. Относится вроде только к зданиям которые на скриншоте.

**Comment by TideSofDarK** [comment]
Спасибо, сейчас займусь.

**Comment by TideSofDarK** [comment]
Проверяйте

**Comment by jappi** [comment]
Больше на работает. А зачем ты поставил лимит на постройки? Убрал самую классную стратегию лейта идущую со времён первых петров, застройка подхода к базе трешом чтобы петя шёл долго до выхода? Мне аж стало грустно =(

**Comment by TideSofDarK** [comment]
Потому что баг абузят с кучей построек - все становится невидимым.

**Comment by jappi** [comment]
Обидно конечно, надеюсь найдётся фикс, петры без застроек проходов не петры :D

**Comment by TideSofDarK** [comment]
Да движок ебанутый, что поделать.

**Comment by jappi** [comment]
Поиграл я в новых вампиров, не знаю видел ли ты или нет, но напишу. Круто придумал с просветом а именно анимацией, видно что тебя просветили. Классно сделана панель в 2 ряда. Собственно это то что можно позаимствовать в петров как мне кажется.

**Comment by jappi** [comment]
Нужен кд на стан секунд 30. Сейчас петра можно держать в пермостане ставя стан под ноги. Так же перестал работать тп петров на базу, просвет и лайфстил.
P.S. вообще так как в варкрафтовских петрах стан это скилл, разумней было бы изначально давать 999 зарядов стана со средним кд.

**Comment by TideSofDarK** [comment]
Пофиксил хуйню с тп и скилами пети
