### ISSUE TITLE
СРОЧНО

### ISSUE THREAD

**Issue by nikita131** [TideSofDarK/PetriReborn#60]
во-1 баг 
![2015-7-31_3-41-29 907](https://cloud.githubusercontent.com/assets/13502966/8998452/2317fbb6-3736-11e5-9696-dbfcf8527d3b.jpg)
во-2 есть человек с ником дудосер и авкой вжлинка он крч поставил курсор на поиск игры и врубил автокликкер . В итоге ему находит лобби и он не принимает! после чего его выкидывает в меню и вновь через кликкер его закидывает в это же лобби.вот, надеюсь понял . И тут явно не 1 человек который это читает с ним сталкивался! у меня он в каждой 10 игре

**Comment by foxyloves** [comment]
во втором,  причём тут разраб карты?
это пиши валв.

**Comment by Kidokyfe** [comment]
про 2 забань его и делов то
