### ISSUE TITLE
Ебашни не работают

### ISSUE THREAD

**Issue by Ammodex** [TideSofDarK/PetriReborn#61]
Ебашни не дамажат, если у пети или у елены есть 2 пиздлявых щита. Я поставил 2 ебашни, 2 башни на понижение армора и 2 башни на криты. Всё апнул до максимального уровня и нихуя. И пете и елене просто похуй на эти башни..

**Comment by TideSofDarK** [comment]
ебашни максил?

**Comment by Ammodex** [comment]
да, замаксил 2 ебашни и нихуя

**Comment by TideSofDarK** [comment]
Что ж там блять, 3300 урона не хватает?

**Comment by foxyloves** [comment]
может они под маской были? :D

**Comment by Ammodex** [comment]
Урона не хватает. Ты попробуй сам поиграй против 2-ух петь хороших, они-то не ебланы, норм собрались. На третью ночь у двоих уже по 1 щиту пиздлявому было. Когда 2 щита появилось, они маски нахуй продали, их ничего не пробивало. Предлагаю в Ебашне совместить свойства 3-ёх башен стихий - замедление, криты и минус армор.

**Comment by foxyloves** [comment]
маски зря продали, они скорость атаки дают.
