### ISSUE TITLE
Лейт КВН

### ISSUE THREAD

**Issue by cvxvpdev** [TideSofDarK/PetriReborn#65]

**Comment by andrushadrochuvdushe** [comment]
Я считаю что петры и зрилы должны быть на равне,ну сделать больше грейдов стены.Потому-что дева мало очень а у пети почти не ограниченные возможности для прокачки

**Comment by foxyloves** [comment]
Башни не пробивают, НО!, выиграть даже против грамотных петров можно, если включить голову.

**Comment by Ammodex** [comment]
Каким образом "включить голову"? Я застраиваюсь там, где длинная лестница, чтоб ломал только один петя. Ставлю по 10 вышек, 3 вышки - криты, 2 - минус армор, ну и 5 ебашен прокачанных. Знач раньше всех апаю себе 275 лвл у мешочка, апаю начальника цеха. Приходит Елена с 3-мя пиздлявыми щитами и начинает ломать стену. Ей просто похуй, похуй на всё - на то, что стену чинят 4 раба, на то, что у меня максимально апнуты заплатки, на то, что у меня 5 ебашен прокачанных.

**Comment by foxyloves** [comment]
> > что стену чинят 4 раба

в этом твоя проблема.

Вот как спокойной затаскивается катка.
![82d9fb0c-36f1-11e5-942e-9ab8b7a864b3](https://cloud.githubusercontent.com/assets/13489856/9023687/d7e42f46-38ae-11e5-95ad-e4b979a91c36.jpg)

**Comment by Ammodex** [comment]
А хук теперь не работает ведь? Такую стену 2 пети снесут как нехуй

**Comment by foxyloves** [comment]
Работает, лол, хук работает, вот сейчас выиграл, против двух петь с 4 щитками последними они были и хер пробили.

**Comment by Ammodex** [comment]
Не пизди

**Comment by foxyloves** [comment]
смысл мне врать?

**Comment by Ammodex** [comment]
чсв епты

**Comment by foxyloves** [comment]
с каких пор прямые руки это чсв?

**Comment by Ammodex** [comment]
чсв...

**Comment by foxyloves** [comment]
ты идиот?
я спокойно выигрываю за петь и за квн.
не вижу сильного дисбаланса.
и я из за этого чсвшник?

**Comment by Ammodex** [comment]
нет, ты чсв по жизни йопта :))))
