### ISSUE TITLE
баг

### ISSUE THREAD

**Issue by nikita131** [TideSofDarK/PetriReborn#66]
я ставлю второй мешок и у меня ломается первый, друг ставил 8 мешков одновременно
![2015-8-2_4-36-59 399](https://cloud.githubusercontent.com/assets/13502966/9024294/9e4ce71a-38d0-11e5-9db6-d10e8f87a23e.jpg)

**Comment by TideSofDarK** [comment]
Спроси что он для этого делал. Мешочек всегда должен быть один

**Comment by nikita131** [comment]
ничего не делал,1 мешок умер ,потом он мог покупать много
