### ISSUE TITLE
нужно больше урона квн`y

### ISSUE THREAD

**Issue by nikita131** [TideSofDarK/PetriReborn#67]
играю на пете покупаю пиздлявый щит и щит небес и 2 замакшеных ебашни под минус армором вообще меня не бьют. мб чуть-чуть пробивают  хп на 400 за минуту или 2 минуты. думаю 4 лвл ебашни на 7к урона нужно добавить. и минус армор добавить доп лвл 
еще нужно сделать все дешевле у квн т.к петей за пару заходов можно збрать 2 босов к 3 ночи и это уже сильный перевес в сторону петров
сорян за ошибки, я очень русский )00

**Comment by foxyloves** [comment]
Один раз такой вот петрович заглянул ко мне и не ушёл ибо был под станом до конца выхода, спасибо бомбам.
А урон этот нахрен не сдался.

**Comment by Ammodex** [comment]
Не слушай его, он чсв и ему раки попадаются. :)

**Comment by foxyloves** [comment]
Не слушай его, он нуб и играть не умеет.. :)
