### ISSUE TITLE
Building on MAC

### ISSUE THREAD

**Issue by lastonoga** [TideSofDarK/PetriReborn#7]
Билдинг на маке не работает вообще.
Вместо здания, только зеленый квадрат, (2) давать себе возможность строить ни к чему не приводит.

**Comment by TideSofDarK** [comment]
Разрешение?

**Comment by lastonoga** [comment]
ultaHD -( 2500 на 1900)

**Comment by TideSofDarK** [comment]
Короче проблема в соотношении сторон. Ответь, ресурсы на иконках показываются?

**Comment by lastonoga** [comment]
Да, но не на всех (вроде), но на некоторых точно есть
Когда сможете починить примерно?

**Comment by TideSofDarK** [comment]
По идее это просто сесть и пару часов посидеть, просто все это время были более жесткие проблемы, короче ждите

**Comment by TideSofDarK** [comment]
Проверяйте, может что исправилось
