### ISSUE TITLE
обнова

### ISSUE THREAD

**Issue by nikita131** [TideSofDarK/PetriReborn#70]
во-1 томба на минус армор стоит афк и не бьет
во-2 на цифру 1 выделяется герой на 2 башни  хотя по идее должны рабы

**Comment by nikita131** [comment]
![2015-8-4_9-52-42 253](https://cloud.githubusercontent.com/assets/13502966/9054924/9bc014d0-3a8e-11e5-965c-5ed93fdf2279.jpg)
одни баги...
зашел в игру и появился сразу во 2 столбике который не квн и не петры
пошло время автостарта и я играл за хуй знает кого

**Comment by nikita131** [comment]
разраб. верни как было 2 дня назад и больше ничего не делай
ибо одни баги
на 1 снимке видно как рабочий просто стоит хотя ему приказано добывать
на некст скринах не работающий минус армор у башни
![2015-8-4_10-0-19 438](https://cloud.githubusercontent.com/assets/13502966/9055122/562ffa28-3a90-11e5-9c08-b24874c78c1e.jpg)
![2015-8-4_10-4-31 789](https://cloud.githubusercontent.com/assets/13502966/9055123/563606a2-3a90-11e5-8616-96c642d3cabb.jpg)
![2015-8-4_10-4-41 450](https://cloud.githubusercontent.com/assets/13502966/9055124/563d2a0e-3a90-11e5-8725-5f46915d41ca.jpg)
снимки были сделаны последовательно и по времени вверху можно это заметить,но минус армор не работает от томбы. 
минус армор на  показателе брони пети, как был сначала так и после нескольких выстрелов томбы не изменился скрин 2 и 3 
НИКАКИХ МОМОВ ДЛЯ ОЧЕНЬ УМНЫХ
далее.
верни что бы было как в доте в настройках у кого стоит цифра 1(у каждого своя) на" выделить главного героя" и цифра 2(у каждого своя) на "выделить всех кроме главного героя"
пусть они работают снова и раньше они выделяли вышки и рабов теперь только вышки!

**Comment by nikita131** [comment]
надеюсь ты что-то понял

**Comment by Ammodex** [comment]
ыыЫФЫЫЫЫЫЫыыыыы) нихуя не вернём, терпи, казак, атаманом станешь!

**Comment by nikita131** [comment]
я думал потерпеть ,сыграл 1 игру зашло за зрителей  и видно было только сломанные деревья
решил 2 раз потерпеть ко мне пришли в первую ночь нихуя не имея и снесли т.к томба вообще не бьет НАЙС БЛЯТЬ НАЙС СУКА

**Comment by nikita131** [comment]
ЗАТО ОН БЛЯТЬ ЛОАДИНГ СКРИН КРАСИВЫМ СДЕЛАЛ

**Comment by nikita131** [comment]
ФВЬФЫЩЭШРА
ЩЗФЩЫОАШРФЪЫА-ШФЫЗЩГРШЪА\Ф
Ы-ШФ,ыюАЬЭФЛЫТАЭДЛФЫРАЭДЛФЫИЭАФТИЫЭЩАОИЫФЖЩАИЫФЖДАЛРТФЫИФП

ЗФИЫПОФЫЛЭПИФЫ
РЗДЛПФИ ДПЗЩОАРЪИЫФ
ШЗО
