### ISSUE TITLE
Лаги

### ISSUE THREAD

**Issue by Ammodex** [TideSofDarK/PetriReborn#76]
Короче, из-за рабов дохуя сильные лаги, попались аутисты, которые сделали овердохуя рабов и было 2 фпс. фикс плиз.

**Comment by TideSofDarK** [comment]
Что ты предлогаешь то? Ограничить колво рабов?

**Comment by Ammodex** [comment]
Ага, а куда деваться? У меня на топовом компе (гта5 на максималках идёт) 10 фпс было всю игру, пока не убил этих рабов.

**Comment by footmah** [comment]
да походу проблемма в постоянных лагах именно из-за этого, любая игра минуте на 10 когда петры еще не начали сносить людей лагает по страшному. Попробуй что нибудь)

**Comment by Ammodex** [comment]
Рили не возможно, по 2 фпс каждую игру

**Comment by Ammodex** [comment]
Я так понял, это ещё из-за того, что они в 2 строятся на одной территории

**Comment by footmah** [comment]
Это тоже было замечено, чем больше на одной территории тем быстрее появляются лаги.

**Comment by TideSofDarK** [comment]
Хм. Лаги ведь только у хоста?

**Comment by Ammodex** [comment]
Нет, лаги у всех

**Comment by footmah** [comment]
Ну они у всех, но зависит скорее всего от хоста. Попадались такие люди которые говорили что встречаются с лагами впервые в петрах хотя переиграл кучу игр и хостил сам и просто заходил и были единичные случаи чтобы не лагало. Рано или поздно скорее всего у любого, даже хоста, залагает если лесорубов очень много.
Тестить не пробовал? мб поможет)
Есть знакомый когда он хостит, лагает у всех но он говорить что у него все отлично.
Попадаются такие катки что у некоторых с первой минуты лагает а у некоторых норм все.

**Comment by Ammodex** [comment]
уберите лаги бля!
