### ISSUE TITLE
Баг с проходом рабочих на базу к петям

### ISSUE THREAD

**Issue by jex398** [TideSofDarK/PetriReborn#78]
Можно пройти рабочим(лесорубом) на базу к петрам, если построить здание на проходе.
Причем, если рабочий туда попал - он может делать ТП на арену и т.д.(ходить в запрещеных местах). 
- Хз каким образом, но вылез из клетки один из мобов (типа тех что на арене). Его может убить обычный квнщик и получить за это голду
  ![2015-08-03_00002](https://cloud.githubusercontent.com/assets/7552596/9156753/b3d97a4e-3eed-11e5-9997-7de2690ae5e0.jpg)

**Comment by K1llMan** [comment]
Мобы вылезают, когда убиваются кнвщиком. Надо бы вообще в клетках их сделать неуязвимыми.

**Comment by Ammodex** [comment]
Так лол, если они вылезут, они будут петь убивать, а пети им ничего не сделают, ведь мобы - неуязвимые.

**Comment by TideSofDarK** [comment]
Мобы в клетках - союзники петь так что все ок, сделаю Что-нибудь
