### ISSUE TITLE
Баг с фармом квнщиком с арены

### ISSUE THREAD

**Issue by jex398** [TideSofDarK/PetriReborn#79]
Можно фармить голд с арены днем и ночью, если рядом с ней поставить вышки с большим ренджом и просветить арену. Просветить арену можно с помощью рабочего как в issue 78
![2015-08-03_00006](https://cloud.githubusercontent.com/assets/7552596/9156788/a5b333d2-3eee-11e5-89d7-cee09b4ff1ba.jpg)

**Comment by jex398** [comment]
Ну или просто зайти на территорию рядом - днём радиуса обзора вроде хватает.

**Comment by TideSofDarK** [comment]
Пофикшено на данный момент, просто апдейт еще не залит.
