### ISSUE TITLE
Брюмастер

### ISSUE THREAD

**Issue by Liminiens** [TideSofDarK/PetriReborn#8]
![2015-07-21_00001](https://cloud.githubusercontent.com/assets/10695322/8802324/58feb37e-2fc9-11e5-9699-fb3f5771a6ea.jpg)

походу кастомка меняет брюмастера на петросяна везде

**Comment by jappi** [comment]
![31123](https://cloud.githubusercontent.com/assets/13433394/8803527/00467af8-2fd0-11e5-80a4-65de542a5d5d.jpg)

**Comment by TideSofDarK** [comment]
Но это же охуенно

**Comment by erickskrauch** [comment]
+1 ))

**Comment by K1llMan** [comment]
Это косяк самой игры, любая кастомка, меняющая имена героев, портит имена в обычной доте.

**Comment by TideSofDarK** [comment]
Да, так оно и есть. Но это еще фигня по сравнению с ломанной локализацией на данный момент.
