### ISSUE TITLE
Тп к мобам не работает

### ISSUE THREAD

**Issue by Ammodex** [TideSofDarK/PetriReborn#81]
Если за петь играет много актёров, то тп к мобам начинает работать через раз. То же самое с тп к боссам, иногда тпшит, иногда нет.

**Comment by Trauin** [comment]
Действительно, если хост лагает то телепорт работает с большими проблемами. Из-за этого петры не могут фармить.

**Comment by Ammodex** [comment]
Хост лагает в 90% и лагает не из-за слабого компа, а из-за доты блять и кол-ва юнитов на карте
